
namespace OphdTechEdit
{
    partial class FormMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMain));
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem1 = new System.Windows.Forms.ToolStripSeparator();
            this.openTechFileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.CloseTechFile = new System.Windows.Forms.ToolStripMenuItem();
            this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripSeparator();
            this.SaveTechFile = new System.Windows.Forms.ToolStripMenuItem();
            this.SaveAsTechFile = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem2 = new System.Windows.Forms.ToolStripSeparator();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.IconList = new System.Windows.Forms.ImageList(this.components);
            this.Panels = new System.Windows.Forms.SplitContainer();
            this.ListCategories = new System.Windows.Forms.ListView();
            this.MenuCategoriesContext = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.MenuCategoriesContextAction = new System.Windows.Forms.ToolStripMenuItem();
            this.CategoryIcons = new System.Windows.Forms.ImageList(this.components);
            this.ListViewTechs = new System.Windows.Forms.ListView();
            this.MenuTechnologiesContext = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.MenuTechnologiesContextAction = new System.Windows.Forms.ToolStripMenuItem();
            this.exportIconsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Panels)).BeginInit();
            this.Panels.Panel1.SuspendLayout();
            this.Panels.Panel2.SuspendLayout();
            this.Panels.SuspendLayout();
            this.MenuCategoriesContext.SuspendLayout();
            this.MenuTechnologiesContext.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(784, 24);
            this.menuStrip1.TabIndex = 1;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newToolStripMenuItem,
            this.toolStripMenuItem1,
            this.openTechFileToolStripMenuItem,
            this.CloseTechFile,
            this.saveToolStripMenuItem,
            this.SaveTechFile,
            this.SaveAsTechFile,
            this.exportIconsToolStripMenuItem,
            this.toolStripMenuItem2,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // newToolStripMenuItem
            // 
            this.newToolStripMenuItem.Name = "newToolStripMenuItem";
            this.newToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.newToolStripMenuItem.Text = "New";
            this.newToolStripMenuItem.Click += new System.EventHandler(this.NewToolStripMenuItem_Click);
            // 
            // toolStripMenuItem1
            // 
            this.toolStripMenuItem1.Name = "toolStripMenuItem1";
            this.toolStripMenuItem1.Size = new System.Drawing.Size(177, 6);
            // 
            // openTechFileToolStripMenuItem
            // 
            this.openTechFileToolStripMenuItem.Name = "openTechFileToolStripMenuItem";
            this.openTechFileToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.openTechFileToolStripMenuItem.Text = "Open Tech File...";
            this.openTechFileToolStripMenuItem.Click += new System.EventHandler(this.OpenTechFileToolStripMenuItem_Click);
            // 
            // CloseTechFile
            // 
            this.CloseTechFile.Name = "CloseTechFile";
            this.CloseTechFile.Size = new System.Drawing.Size(180, 22);
            this.CloseTechFile.Text = "Close";
            this.CloseTechFile.Click += new System.EventHandler(this.CloseTechFile_Click);
            // 
            // saveToolStripMenuItem
            // 
            this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            this.saveToolStripMenuItem.Size = new System.Drawing.Size(177, 6);
            // 
            // SaveTechFile
            // 
            this.SaveTechFile.Name = "SaveTechFile";
            this.SaveTechFile.Size = new System.Drawing.Size(180, 22);
            this.SaveTechFile.Text = "Save";
            this.SaveTechFile.Click += new System.EventHandler(this.SaveTechFile_Click);
            // 
            // SaveAsTechFile
            // 
            this.SaveAsTechFile.Name = "SaveAsTechFile";
            this.SaveAsTechFile.Size = new System.Drawing.Size(180, 22);
            this.SaveAsTechFile.Text = "Save As...";
            this.SaveAsTechFile.Click += new System.EventHandler(this.SaveAsTechFile_Click);
            // 
            // toolStripMenuItem2
            // 
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new System.Drawing.Size(177, 6);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.aboutToolStripMenuItem.Text = "About...";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.AboutToolStripMenuItem_Click);
            // 
            // IconList
            // 
            this.IconList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("IconList.ImageStream")));
            this.IconList.TransparentColor = System.Drawing.Color.Transparent;
            this.IconList.Images.SetKeyName(0, "001-binary-code.png");
            this.IconList.Images.SetKeyName(1, "001-fertilizer.png");
            this.IconList.Images.SetKeyName(2, "001-gas-tank.png");
            this.IconList.Images.SetKeyName(3, "001-mining.png");
            this.IconList.Images.SetKeyName(4, "001-molecule.png");
            this.IconList.Images.SetKeyName(5, "001-nuclear.png");
            this.IconList.Images.SetKeyName(6, "001-plant.png");
            this.IconList.Images.SetKeyName(7, "001-satellite.png");
            this.IconList.Images.SetKeyName(8, "002-air-filter.png");
            this.IconList.Images.SetKeyName(9, "002-binary-code-1.png");
            this.IconList.Images.SetKeyName(10, "002-field.png");
            this.IconList.Images.SetKeyName(11, "002-funnel.png");
            this.IconList.Images.SetKeyName(12, "002-gas-mask.png");
            this.IconList.Images.SetKeyName(13, "002-membrane.png");
            this.IconList.Images.SetKeyName(14, "002-nuclear-power.png");
            this.IconList.Images.SetKeyName(15, "002-plant.png");
            this.IconList.Images.SetKeyName(16, "002-satellite-1.png");
            this.IconList.Images.SetKeyName(17, "003-binary-code-2.png");
            this.IconList.Images.SetKeyName(18, "003-gas.png");
            this.IconList.Images.SetKeyName(19, "003-lens.png");
            this.IconList.Images.SetKeyName(20, "003-mine.png");
            this.IconList.Images.SetKeyName(21, "003-nanotechnology.png");
            this.IconList.Images.SetKeyName(22, "003-pregnancy.png");
            this.IconList.Images.SetKeyName(23, "003-satellite-2.png");
            this.IconList.Images.SetKeyName(24, "003-virtual-reality.png");
            this.IconList.Images.SetKeyName(25, "004-asteroid.png");
            this.IconList.Images.SetKeyName(26, "004-fence.png");
            this.IconList.Images.SetKeyName(27, "004-gear.png");
            this.IconList.Images.SetKeyName(28, "004-ovum.png");
            this.IconList.Images.SetKeyName(29, "004-space-station.png");
            this.IconList.Images.SetKeyName(30, "004-time-machine.png");
            this.IconList.Images.SetKeyName(31, "004-transparent.png");
            this.IconList.Images.SetKeyName(32, "004-virus.png");
            this.IconList.Images.SetKeyName(33, "005-asteroid-1.png");
            this.IconList.Images.SetKeyName(34, "005-dna.png");
            this.IconList.Images.SetKeyName(35, "005-dna-test.png");
            this.IconList.Images.SetKeyName(36, "005-nanotechnology-1.png");
            this.IconList.Images.SetKeyName(37, "005-plumbing.png");
            this.IconList.Images.SetKeyName(38, "005-program.png");
            this.IconList.Images.SetKeyName(39, "005-satellite-3.png");
            this.IconList.Images.SetKeyName(40, "005-space-station.png");
            this.IconList.Images.SetKeyName(41, "005-table-lamp.png");
            this.IconList.Images.SetKeyName(42, "006-asteroid-belt.png");
            this.IconList.Images.SetKeyName(43, "006-blocks.png");
            this.IconList.Images.SetKeyName(44, "006-chromosome.png");
            this.IconList.Images.SetKeyName(45, "006-color.png");
            this.IconList.Images.SetKeyName(46, "006-data.png");
            this.IconList.Images.SetKeyName(47, "006-molecular-medicine.png");
            this.IconList.Images.SetKeyName(48, "006-satellite-4.png");
            this.IconList.Images.SetKeyName(49, "007-cloud.png");
            this.IconList.Images.SetKeyName(50, "007-code-error.png");
            this.IconList.Images.SetKeyName(51, "007-crane.png");
            this.IconList.Images.SetKeyName(52, "007-feeder.png");
            this.IconList.Images.SetKeyName(53, "007-galaxy.png");
            this.IconList.Images.SetKeyName(54, "007-gmo-food.png");
            this.IconList.Images.SetKeyName(55, "007-mode.png");
            this.IconList.Images.SetKeyName(56, "007-nanocrystal.png");
            this.IconList.Images.SetKeyName(57, "007-poster.png");
            this.IconList.Images.SetKeyName(58, "008-anesthesia.png");
            this.IconList.Images.SetKeyName(59, "008-chromosome-1.png");
            this.IconList.Images.SetKeyName(60, "008-cloud-1.png");
            this.IconList.Images.SetKeyName(61, "008-coding.png");
            this.IconList.Images.SetKeyName(62, "008-contactless.png");
            this.IconList.Images.SetKeyName(63, "008-folder.png");
            this.IconList.Images.SetKeyName(64, "008-nano-3d-printer.png");
            this.IconList.Images.SetKeyName(65, "008-satellite-5.png");
            this.IconList.Images.SetKeyName(66, "008-space-capsule.png");
            this.IconList.Images.SetKeyName(67, "009-binary-code-3.png");
            this.IconList.Images.SetKeyName(68, "009-book.png");
            this.IconList.Images.SetKeyName(69, "009-circular-saw.png");
            this.IconList.Images.SetKeyName(70, "009-gene.png");
            this.IconList.Images.SetKeyName(71, "009-nanotechnology-2.png");
            this.IconList.Images.SetKeyName(72, "009-smog.png");
            this.IconList.Images.SetKeyName(73, "009-space-station-1.png");
            this.IconList.Images.SetKeyName(74, "009-theater.png");
            this.IconList.Images.SetKeyName(75, "009-ultrasound.png");
            this.IconList.Images.SetKeyName(76, "010-calendar.png");
            this.IconList.Images.SetKeyName(77, "010-commit-git.png");
            this.IconList.Images.SetKeyName(78, "010-compass.png");
            this.IconList.Images.SetKeyName(79, "010-nanotechnology-3.png");
            this.IconList.Images.SetKeyName(80, "010-pincer.png");
            this.IconList.Images.SetKeyName(81, "010-satellite.png");
            this.IconList.Images.SetKeyName(82, "010-satellite-dish.png");
            this.IconList.Images.SetKeyName(83, "010-test-tube.png");
            this.IconList.Images.SetKeyName(84, "011-air-conditioner.png");
            this.IconList.Images.SetKeyName(85, "011-caution-sign.png");
            this.IconList.Images.SetKeyName(86, "011-error.png");
            this.IconList.Images.SetKeyName(87, "011-genes.png");
            this.IconList.Images.SetKeyName(88, "011-pills.png");
            this.IconList.Images.SetKeyName(89, "011-plant.png");
            this.IconList.Images.SetKeyName(90, "011-satellite-6.png");
            this.IconList.Images.SetKeyName(91, "011-shrimp.png");
            this.IconList.Images.SetKeyName(92, "012-biomaterials.png");
            this.IconList.Images.SetKeyName(93, "012-blood-cells.png");
            this.IconList.Images.SetKeyName(94, "012-earth.png");
            this.IconList.Images.SetKeyName(95, "012-gateway.png");
            this.IconList.Images.SetKeyName(96, "012-jellyfish.png");
            this.IconList.Images.SetKeyName(97, "012-robot.png");
            this.IconList.Images.SetKeyName(98, "012-screws.png");
            this.IconList.Images.SetKeyName(99, "012-space-station-2.png");
            this.IconList.Images.SetKeyName(100, "013-constellation.png");
            this.IconList.Images.SetKeyName(101, "013-gears.png");
            this.IconList.Images.SetKeyName(102, "013-gene-1.png");
            this.IconList.Images.SetKeyName(103, "013-industrial-robot.png");
            this.IconList.Images.SetKeyName(104, "013-light-bulb.png");
            this.IconList.Images.SetKeyName(105, "013-monitor.png");
            this.IconList.Images.SetKeyName(106, "013-nanosensor.png");
            this.IconList.Images.SetKeyName(107, "013-surgery-robot.png");
            this.IconList.Images.SetKeyName(108, "014-broken-pipe.png");
            this.IconList.Images.SetKeyName(109, "014-chromosomes.png");
            this.IconList.Images.SetKeyName(110, "014-content-management.png");
            this.IconList.Images.SetKeyName(111, "014-defrost.png");
            this.IconList.Images.SetKeyName(112, "014-hardware.png");
            this.IconList.Images.SetKeyName(113, "014-microscope.png");
            this.IconList.Images.SetKeyName(114, "014-prosthetic.png");
            this.IconList.Images.SetKeyName(115, "014-robotic-arm.png");
            this.IconList.Images.SetKeyName(116, "015-construction.png");
            this.IconList.Images.SetKeyName(117, "015-flowchart.png");
            this.IconList.Images.SetKeyName(118, "015-industrial.png");
            this.IconList.Images.SetKeyName(119, "015-nanosensor-1.png");
            this.IconList.Images.SetKeyName(120, "015-project.png");
            this.IconList.Images.SetKeyName(121, "015-safe-box.png");
            this.IconList.Images.SetKeyName(122, "015-surgery.png");
            this.IconList.Images.SetKeyName(123, "015-test-tubes.png");
            this.IconList.Images.SetKeyName(124, "016-chemicals.png");
            this.IconList.Images.SetKeyName(125, "016-erythrocytes.png");
            this.IconList.Images.SetKeyName(126, "016-generator.png");
            this.IconList.Images.SetKeyName(127, "016-project-1.png");
            this.IconList.Images.SetKeyName(128, "016-robot-assistant.png");
            this.IconList.Images.SetKeyName(129, "016-vertical-garden.png");
            this.IconList.Images.SetKeyName(130, "016-virus.png");
            this.IconList.Images.SetKeyName(131, "016-windy.png");
            this.IconList.Images.SetKeyName(132, "017-cctv.png");
            this.IconList.Images.SetKeyName(133, "017-dna-test-1.png");
            this.IconList.Images.SetKeyName(134, "017-microscope-1.png");
            this.IconList.Images.SetKeyName(135, "017-rain.png");
            this.IconList.Images.SetKeyName(136, "017-robot-1.png");
            this.IconList.Images.SetKeyName(137, "017-syringe.png");
            this.IconList.Images.SetKeyName(138, "017-transparent.png");
            this.IconList.Images.SetKeyName(139, "017-virus.png");
            this.IconList.Images.SetKeyName(140, "018-bacterias.png");
            this.IconList.Images.SetKeyName(141, "018-book-shelf.png");
            this.IconList.Images.SetKeyName(142, "018-comparing.png");
            this.IconList.Images.SetKeyName(143, "018-dna-strand.png");
            this.IconList.Images.SetKeyName(144, "018-engine.png");
            this.IconList.Images.SetKeyName(145, "018-nanomedicine.png");
            this.IconList.Images.SetKeyName(146, "018-suspension.png");
            this.IconList.Images.SetKeyName(147, "018-virus-1.png");
            this.IconList.Images.SetKeyName(148, "019-cable.png");
            this.IconList.Images.SetKeyName(149, "019-microscope-2.png");
            this.IconList.Images.SetKeyName(150, "019-robot-2.png");
            this.IconList.Images.SetKeyName(151, "019-round-chart.png");
            this.IconList.Images.SetKeyName(152, "019-serology-test.png");
            this.IconList.Images.SetKeyName(153, "019-server.png");
            this.IconList.Images.SetKeyName(154, "019-solar-panel.png");
            this.IconList.Images.SetKeyName(155, "019-urban-garden.png");
            this.IconList.Images.SetKeyName(156, "020-coronavirus.png");
            this.IconList.Images.SetKeyName(157, "020-gear.png");
            this.IconList.Images.SetKeyName(158, "020-medical-research.png");
            this.IconList.Images.SetKeyName(159, "020-microscope-3.png");
            this.IconList.Images.SetKeyName(160, "020-rt-pcr-machine.png");
            this.IconList.Images.SetKeyName(161, "020-sign.png");
            this.IconList.Images.SetKeyName(162, "020-troubleshooting.png");
            this.IconList.Images.SetKeyName(163, "020-wifi.png");
            this.IconList.Images.SetKeyName(164, "021-air-cooler.png");
            this.IconList.Images.SetKeyName(165, "021-algorithm.png");
            this.IconList.Images.SetKeyName(166, "021-artificial-heart.png");
            this.IconList.Images.SetKeyName(167, "021-bacteria.png");
            this.IconList.Images.SetKeyName(168, "021-eye.png");
            this.IconList.Images.SetKeyName(169, "021-fence.png");
            this.IconList.Images.SetKeyName(170, "021-microscope-4.png");
            this.IconList.Images.SetKeyName(171, "021-oven.png");
            this.IconList.Images.SetKeyName(172, "022-battery.png");
            this.IconList.Images.SetKeyName(173, "022-brain.png");
            this.IconList.Images.SetKeyName(174, "022-bribe.png");
            this.IconList.Images.SetKeyName(175, "022-meteor.png");
            this.IconList.Images.SetKeyName(176, "022-microscope-5.png");
            this.IconList.Images.SetKeyName(177, "022-transparent.png");
            this.IconList.Images.SetKeyName(178, "022-virus-2.png");
            this.IconList.Images.SetKeyName(179, "022-waste.png");
            this.IconList.Images.SetKeyName(180, "023-carnival-mask.png");
            this.IconList.Images.SetKeyName(181, "023-cctv-1.png");
            this.IconList.Images.SetKeyName(182, "023-circuit.png");
            this.IconList.Images.SetKeyName(183, "023-lungs.png");
            this.IconList.Images.SetKeyName(184, "023-machine.png");
            this.IconList.Images.SetKeyName(185, "023-park.png");
            this.IconList.Images.SetKeyName(186, "023-robotic-hand.png");
            this.IconList.Images.SetKeyName(187, "023-valve.png");
            this.IconList.Images.SetKeyName(188, "024-covid-test.png");
            this.IconList.Images.SetKeyName(189, "024-crane-machine.png");
            this.IconList.Images.SetKeyName(190, "024-drone.png");
            this.IconList.Images.SetKeyName(191, "024-graphic.png");
            this.IconList.Images.SetKeyName(192, "024-microchip.png");
            this.IconList.Images.SetKeyName(193, "024-power.png");
            this.IconList.Images.SetKeyName(194, "024-robotic-hand-1.png");
            this.IconList.Images.SetKeyName(195, "024-romantic-dinner.png");
            this.IconList.Images.SetKeyName(196, "025-bio-sensor.png");
            this.IconList.Images.SetKeyName(197, "025-circuit.png");
            this.IconList.Images.SetKeyName(198, "025-drill.png");
            this.IconList.Images.SetKeyName(199, "025-robot-3.png");
            this.IconList.Images.SetKeyName(200, "025-transition.png");
            this.IconList.Images.SetKeyName(201, "025-virus-3.png");
            this.IconList.Images.SetKeyName(202, "026-binoculars.png");
            this.IconList.Images.SetKeyName(203, "026-bonsai.png");
            this.IconList.Images.SetKeyName(204, "026-drill-1.png");
            this.IconList.Images.SetKeyName(205, "026-microchip-1.png");
            this.IconList.Images.SetKeyName(206, "026-molecule.png");
            this.IconList.Images.SetKeyName(207, "026-robotic-arm-1.png");
            this.IconList.Images.SetKeyName(208, "026-virus-4.png");
            this.IconList.Images.SetKeyName(209, "027-accumulator.png");
            this.IconList.Images.SetKeyName(210, "027-artificial-intelligence.png");
            this.IconList.Images.SetKeyName(211, "027-compass.png");
            this.IconList.Images.SetKeyName(212, "027-greens.png");
            this.IconList.Images.SetKeyName(213, "027-malware.png");
            this.IconList.Images.SetKeyName(214, "027-microchip-2.png");
            this.IconList.Images.SetKeyName(215, "027-mine.png");
            this.IconList.Images.SetKeyName(216, "027-radiotherapy.png");
            this.IconList.Images.SetKeyName(217, "028-bacteria-1.png");
            this.IconList.Images.SetKeyName(218, "028-bionic-eye.png");
            this.IconList.Images.SetKeyName(219, "028-electric-tower.png");
            this.IconList.Images.SetKeyName(220, "028-eye.png");
            this.IconList.Images.SetKeyName(221, "028-machine.png");
            this.IconList.Images.SetKeyName(222, "028-plug.png");
            this.IconList.Images.SetKeyName(223, "028-responsive.png");
            this.IconList.Images.SetKeyName(224, "028-snowflake.png");
            this.IconList.Images.SetKeyName(225, "029-air-conditioning.png");
            this.IconList.Images.SetKeyName(226, "029-battery-1.png");
            this.IconList.Images.SetKeyName(227, "029-chip.png");
            this.IconList.Images.SetKeyName(228, "029-crane.png");
            this.IconList.Images.SetKeyName(229, "029-medal.png");
            this.IconList.Images.SetKeyName(230, "029-microscope.png");
            this.IconList.Images.SetKeyName(231, "029-robotic-arm.png");
            this.IconList.Images.SetKeyName(232, "029-thermometer.png");
            this.IconList.Images.SetKeyName(233, "030-apps.png");
            this.IconList.Images.SetKeyName(234, "030-conveyor.png");
            this.IconList.Images.SetKeyName(235, "030-cpu.png");
            this.IconList.Images.SetKeyName(236, "030-dna-strand.png");
            this.IconList.Images.SetKeyName(237, "030-heart-rate.png");
            this.IconList.Images.SetKeyName(238, "030-industrial-robot.png");
            this.IconList.Images.SetKeyName(239, "030-law.png");
            this.IconList.Images.SetKeyName(240, "031-analytics.png");
            this.IconList.Images.SetKeyName(241, "031-cpu-1.png");
            this.IconList.Images.SetKeyName(242, "031-planet.png");
            this.IconList.Images.SetKeyName(243, "031-recycling.png");
            this.IconList.Images.SetKeyName(244, "031-robotic-leg.png");
            this.IconList.Images.SetKeyName(245, "031-vase.png");
            this.IconList.Images.SetKeyName(246, "031-virus-5.png");
            this.IconList.Images.SetKeyName(247, "032-books.png");
            this.IconList.Images.SetKeyName(248, "032-flowchart.png");
            this.IconList.Images.SetKeyName(249, "032-industrial-robot-1.png");
            this.IconList.Images.SetKeyName(250, "032-microprocessor.png");
            this.IconList.Images.SetKeyName(251, "032-microservice.png");
            this.IconList.Images.SetKeyName(252, "032-radiation.png");
            this.IconList.Images.SetKeyName(253, "032-report.png");
            this.IconList.Images.SetKeyName(254, "033-computer.png");
            this.IconList.Images.SetKeyName(255, "033-conclusion.png");
            this.IconList.Images.SetKeyName(256, "033-covid-test-1.png");
            this.IconList.Images.SetKeyName(257, "033-exchange.png");
            this.IconList.Images.SetKeyName(258, "033-pc.png");
            this.IconList.Images.SetKeyName(259, "033-privacy.png");
            this.IconList.Images.SetKeyName(260, "033-prosthesis.png");
            this.IconList.Images.SetKeyName(261, "034-bacteria-2.png");
            this.IconList.Images.SetKeyName(262, "034-cloud.png");
            this.IconList.Images.SetKeyName(263, "034-constellation.png");
            this.IconList.Images.SetKeyName(264, "034-gear-1.png");
            this.IconList.Images.SetKeyName(265, "034-manipulator.png");
            this.IconList.Images.SetKeyName(266, "034-presentation.png");
            this.IconList.Images.SetKeyName(267, "034-radio-button.png");
            this.IconList.Images.SetKeyName(268, "035-blood-test.png");
            this.IconList.Images.SetKeyName(269, "035-cpu-2.png");
            this.IconList.Images.SetKeyName(270, "035-data-lake.png");
            this.IconList.Images.SetKeyName(271, "035-robots-and-humans.png");
            this.IconList.Images.SetKeyName(272, "035-rocket.png");
            this.IconList.Images.SetKeyName(273, "035-virus-6.png");
            this.IconList.Images.SetKeyName(274, "036-coronavirus-1.png");
            this.IconList.Images.SetKeyName(275, "036-expression.png");
            this.IconList.Images.SetKeyName(276, "036-map.png");
            this.IconList.Images.SetKeyName(277, "036-processor.png");
            this.IconList.Images.SetKeyName(278, "036-robotic-arm-1.png");
            this.IconList.Images.SetKeyName(279, "036-ruler.png");
            this.IconList.Images.SetKeyName(280, "036-trading.png");
            this.IconList.Images.SetKeyName(281, "037-electrocardiogram.png");
            this.IconList.Images.SetKeyName(282, "037-no-results.png");
            this.IconList.Images.SetKeyName(283, "037-processor-1.png");
            this.IconList.Images.SetKeyName(284, "037-robotic-limb.png");
            this.IconList.Images.SetKeyName(285, "037-virus-7.png");
            this.IconList.Images.SetKeyName(286, "038-brain.png");
            this.IconList.Images.SetKeyName(287, "038-cpu-3.png");
            this.IconList.Images.SetKeyName(288, "038-files.png");
            this.IconList.Images.SetKeyName(289, "038-growth.png");
            this.IconList.Images.SetKeyName(290, "038-microscope.png");
            this.IconList.Images.SetKeyName(291, "038-music-notes.png");
            this.IconList.Images.SetKeyName(292, "038-virus-8.png");
            this.IconList.Images.SetKeyName(293, "039-aggregation.png");
            this.IconList.Images.SetKeyName(294, "039-chip-1.png");
            this.IconList.Images.SetKeyName(295, "039-communications.png");
            this.IconList.Images.SetKeyName(296, "039-industrial-robot-2.png");
            this.IconList.Images.SetKeyName(297, "039-line-chart.png");
            this.IconList.Images.SetKeyName(298, "039-stool-test.png");
            this.IconList.Images.SetKeyName(299, "039-virus-9.png");
            this.IconList.Images.SetKeyName(300, "040-bee.png");
            this.IconList.Images.SetKeyName(301, "040-chip-2.png");
            this.IconList.Images.SetKeyName(302, "040-employee.png");
            this.IconList.Images.SetKeyName(303, "040-fight.png");
            this.IconList.Images.SetKeyName(304, "040-vaccination.png");
            this.IconList.Images.SetKeyName(305, "040-virus.png");
            this.IconList.Images.SetKeyName(306, "041-artificial-intelligence.png");
            this.IconList.Images.SetKeyName(307, "041-butterfly.png");
            this.IconList.Images.SetKeyName(308, "041-earth.png");
            this.IconList.Images.SetKeyName(309, "041-microscope.png");
            this.IconList.Images.SetKeyName(310, "041-slave.png");
            this.IconList.Images.SetKeyName(311, "041-telescope.png");
            this.IconList.Images.SetKeyName(312, "041-virus-10.png");
            this.IconList.Images.SetKeyName(313, "042-ant.png");
            this.IconList.Images.SetKeyName(314, "042-curtains.png");
            this.IconList.Images.SetKeyName(315, "042-motherboard.png");
            this.IconList.Images.SetKeyName(316, "042-power-button.png");
            this.IconList.Images.SetKeyName(317, "042-protest.png");
            this.IconList.Images.SetKeyName(318, "042-research.png");
            this.IconList.Images.SetKeyName(319, "042-swab.png");
            this.IconList.Images.SetKeyName(320, "043-coding.png");
            this.IconList.Images.SetKeyName(321, "043-concept.png");
            this.IconList.Images.SetKeyName(322, "043-equal.png");
            this.IconList.Images.SetKeyName(323, "043-insect.png");
            this.IconList.Images.SetKeyName(324, "043-laptop.png");
            this.IconList.Images.SetKeyName(325, "043-links.png");
            this.IconList.Images.SetKeyName(326, "043-microscope-1.png");
            this.IconList.Images.SetKeyName(327, "044-analysis-1.png");
            this.IconList.Images.SetKeyName(328, "044-bee-1.png");
            this.IconList.Images.SetKeyName(329, "044-dashboard.png");
            this.IconList.Images.SetKeyName(330, "044-global-learning.png");
            this.IconList.Images.SetKeyName(331, "044-plankton.png");
            this.IconList.Images.SetKeyName(332, "044-processor-2.png");
            this.IconList.Images.SetKeyName(333, "044-world.png");
            this.IconList.Images.SetKeyName(334, "045-branch.png");
            this.IconList.Images.SetKeyName(335, "045-business-plan.png");
            this.IconList.Images.SetKeyName(336, "045-cell.png");
            this.IconList.Images.SetKeyName(337, "045-cutting.png");
            this.IconList.Images.SetKeyName(338, "045-give-love.png");
            this.IconList.Images.SetKeyName(339, "045-globe.png");
            this.IconList.Images.SetKeyName(340, "045-worm.png");
            this.IconList.Images.SetKeyName(341, "046-flowchart.png");
            this.IconList.Images.SetKeyName(342, "046-knowledge.png");
            this.IconList.Images.SetKeyName(343, "046-map.png");
            this.IconList.Images.SetKeyName(344, "046-measurer.png");
            this.IconList.Images.SetKeyName(345, "046-mri.png");
            this.IconList.Images.SetKeyName(346, "046-parasite.png");
            this.IconList.Images.SetKeyName(347, "046-peace.png");
            this.IconList.Images.SetKeyName(348, "047-beehive.png");
            this.IconList.Images.SetKeyName(349, "047-drone-1.png");
            this.IconList.Images.SetKeyName(350, "047-laser.png");
            this.IconList.Images.SetKeyName(351, "047-microorganisms.png");
            this.IconList.Images.SetKeyName(352, "047-online-learning.png");
            this.IconList.Images.SetKeyName(353, "047-presentation-1.png");
            this.IconList.Images.SetKeyName(354, "047-right-to-life.png");
            this.IconList.Images.SetKeyName(355, "048-bee-2.png");
            this.IconList.Images.SetKeyName(356, "048-eye.png");
            this.IconList.Images.SetKeyName(357, "048-liberty.png");
            this.IconList.Images.SetKeyName(358, "048-plasma-ball.png");
            this.IconList.Images.SetKeyName(359, "048-process.png");
            this.IconList.Images.SetKeyName(360, "048-teacher.png");
            this.IconList.Images.SetKeyName(361, "048-vaccination-1.png");
            this.IconList.Images.SetKeyName(362, "049-ant-1.png");
            this.IconList.Images.SetKeyName(363, "049-coronavirus-2.png");
            this.IconList.Images.SetKeyName(364, "049-flowchart-1.png");
            this.IconList.Images.SetKeyName(365, "049-list.png");
            this.IconList.Images.SetKeyName(366, "049-monstera.png");
            this.IconList.Images.SetKeyName(367, "049-smog.png");
            this.IconList.Images.SetKeyName(368, "049-spaceship.png");
            this.IconList.Images.SetKeyName(369, "050-ant-2.png");
            this.IconList.Images.SetKeyName(370, "050-kalanchoe.png");
            this.IconList.Images.SetKeyName(371, "050-poetry.png");
            this.IconList.Images.SetKeyName(372, "050-research.png");
            this.IconList.Images.SetKeyName(373, "050-thunderstorm.png");
            this.IconList.Images.SetKeyName(374, "050-uml.png");
            this.IconList.Images.SetKeyName(375, "051-bacteria-3.png");
            this.IconList.Images.SetKeyName(376, "051-chip.png");
            this.IconList.Images.SetKeyName(377, "051-cloudy.png");
            this.IconList.Images.SetKeyName(378, "051-stag-beetle.png");
            this.IconList.Images.SetKeyName(379, "051-study-tools.png");
            this.IconList.Images.SetKeyName(380, "051-uml-1.png");
            this.IconList.Images.SetKeyName(381, "051-wax.png");
            this.IconList.Images.SetKeyName(382, "052-acne.png");
            this.IconList.Images.SetKeyName(383, "052-artificial-intelligence.png");
            this.IconList.Images.SetKeyName(384, "052-digital-key.png");
            this.IconList.Images.SetKeyName(385, "052-impairment.png");
            this.IconList.Images.SetKeyName(386, "052-ladybug.png");
            this.IconList.Images.SetKeyName(387, "052-pollution.png");
            this.IconList.Images.SetKeyName(388, "052-science.png");
            this.IconList.Images.SetKeyName(389, "053-air-filter.png");
            this.IconList.Images.SetKeyName(390, "053-bacteria-4.png");
            this.IconList.Images.SetKeyName(391, "053-brain-1.png");
            this.IconList.Images.SetKeyName(392, "053-iot.png");
            this.IconList.Images.SetKeyName(393, "053-potato-bug.png");
            this.IconList.Images.SetKeyName(394, "053-soil.png");
            this.IconList.Images.SetKeyName(395, "053-timeline.png");
            this.IconList.Images.SetKeyName(396, "054-air-filter-1.png");
            this.IconList.Images.SetKeyName(397, "054-artificial-intelligence-1.png");
            this.IconList.Images.SetKeyName(398, "054-covid-test-2.png");
            this.IconList.Images.SetKeyName(399, "054-innovation.png");
            this.IconList.Images.SetKeyName(400, "054-insect-1.png");
            this.IconList.Images.SetKeyName(401, "054-microservice-1.png");
            this.IconList.Images.SetKeyName(402, "054-planetary.png");
            this.IconList.Images.SetKeyName(403, "055-acid-rain.png");
            this.IconList.Images.SetKeyName(404, "055-artificial-intelligence-2.png");
            this.IconList.Images.SetKeyName(405, "055-bug.png");
            this.IconList.Images.SetKeyName(406, "055-microservice-2.png");
            this.IconList.Images.SetKeyName(407, "055-mold.png");
            this.IconList.Images.SetKeyName(408, "055-virtual.png");
            this.IconList.Images.SetKeyName(409, "055-workspace.png");
            this.IconList.Images.SetKeyName(410, "056-antivirus.png");
            this.IconList.Images.SetKeyName(411, "056-biohazard.png");
            this.IconList.Images.SetKeyName(412, "056-brain-2.png");
            this.IconList.Images.SetKeyName(413, "056-coronavirus-3.png");
            this.IconList.Images.SetKeyName(414, "056-material.png");
            this.IconList.Images.SetKeyName(415, "056-prosthetic.png");
            this.IconList.Images.SetKeyName(416, "056-radioactive.png");
            this.IconList.Images.SetKeyName(417, "057-acid-rain-1.png");
            this.IconList.Images.SetKeyName(418, "057-bacteria-5.png");
            this.IconList.Images.SetKeyName(419, "057-defrost-1.png");
            this.IconList.Images.SetKeyName(420, "057-hazardous.png");
            this.IconList.Images.SetKeyName(421, "057-praying-mantis.png");
            this.IconList.Images.SetKeyName(422, "057-robots-and-humans.png");
            this.IconList.Images.SetKeyName(423, "057-shower.png");
            this.IconList.Images.SetKeyName(424, "058-centipede.png");
            this.IconList.Images.SetKeyName(425, "058-cyber.png");
            this.IconList.Images.SetKeyName(426, "058-data-lake-1.png");
            this.IconList.Images.SetKeyName(427, "058-leaves.png");
            this.IconList.Images.SetKeyName(428, "058-test.png");
            this.IconList.Images.SetKeyName(429, "058-toxic.png");
            this.IconList.Images.SetKeyName(430, "059-biohazard-1.png");
            this.IconList.Images.SetKeyName(431, "059-brain-3.png");
            this.IconList.Images.SetKeyName(432, "059-data-lake-2.png");
            this.IconList.Images.SetKeyName(433, "059-green-energy.png");
            this.IconList.Images.SetKeyName(434, "059-support.png");
            this.IconList.Images.SetKeyName(435, "059-virus-1.png");
            this.IconList.Images.SetKeyName(436, "060-biotechnology.png");
            this.IconList.Images.SetKeyName(437, "060-brain-4.png");
            this.IconList.Images.SetKeyName(438, "060-cooling-system.png");
            this.IconList.Images.SetKeyName(439, "060-illumination.png");
            this.IconList.Images.SetKeyName(440, "060-prosthetic-1.png");
            this.IconList.Images.SetKeyName(441, "060-radiation.png");
            this.IconList.Images.SetKeyName(442, "061-atom.png");
            this.IconList.Images.SetKeyName(443, "061-brain-5.png");
            this.IconList.Images.SetKeyName(444, "061-conditioner.png");
            this.IconList.Images.SetKeyName(445, "061-flux.png");
            this.IconList.Images.SetKeyName(446, "061-hazard.png");
            this.IconList.Images.SetKeyName(447, "061-valve.png");
            this.IconList.Images.SetKeyName(448, "062-carbon.png");
            this.IconList.Images.SetKeyName(449, "062-gas-mask.png");
            this.IconList.Images.SetKeyName(450, "062-gear.png");
            this.IconList.Images.SetKeyName(451, "062-no-results-1.png");
            this.IconList.Images.SetKeyName(452, "062-pipes.png");
            this.IconList.Images.SetKeyName(453, "063-aggregation-1.png");
            this.IconList.Images.SetKeyName(454, "063-air-cooler.png");
            this.IconList.Images.SetKeyName(455, "063-physics.png");
            this.IconList.Images.SetKeyName(456, "063-plant-1.png");
            this.IconList.Images.SetKeyName(457, "063-protection.png");
            this.IconList.Images.SetKeyName(458, "063-robot.png");
            this.IconList.Images.SetKeyName(459, "064-atom-1.png");
            this.IconList.Images.SetKeyName(460, "064-autism.png");
            this.IconList.Images.SetKeyName(461, "064-brain-6.png");
            this.IconList.Images.SetKeyName(462, "064-gas-mask-1.png");
            this.IconList.Images.SetKeyName(463, "064-seeds.png");
            this.IconList.Images.SetKeyName(464, "064-solar-panel.png");
            this.IconList.Images.SetKeyName(465, "065-atom-2.png");
            this.IconList.Images.SetKeyName(466, "065-cyborg.png");
            this.IconList.Images.SetKeyName(467, "065-gas-mask-2.png");
            this.IconList.Images.SetKeyName(468, "065-solar-system.png");
            this.IconList.Images.SetKeyName(469, "065-talk.png");
            this.IconList.Images.SetKeyName(470, "065-time-machine-1.png");
            this.IconList.Images.SetKeyName(471, "066-aggregation-2.png");
            this.IconList.Images.SetKeyName(472, "066-galaxy.png");
            this.IconList.Images.SetKeyName(473, "066-hands.png");
            this.IconList.Images.SetKeyName(474, "066-hazardous.png");
            this.IconList.Images.SetKeyName(475, "066-mind-mapping.png");
            this.IconList.Images.SetKeyName(476, "066-nanotechnology.png");
            this.IconList.Images.SetKeyName(477, "067-atom-3.png");
            this.IconList.Images.SetKeyName(478, "067-brain-7.png");
            this.IconList.Images.SetKeyName(479, "067-pills.png");
            this.IconList.Images.SetKeyName(480, "067-slave-1.png");
            this.IconList.Images.SetKeyName(481, "067-spores.png");
            this.IconList.Images.SetKeyName(482, "067-waste.png");
            this.IconList.Images.SetKeyName(483, "068-chip-1.png");
            this.IconList.Images.SetKeyName(484, "068-control-room.png");
            this.IconList.Images.SetKeyName(485, "068-nuclear.png");
            this.IconList.Images.SetKeyName(486, "068-petri-dish.png");
            this.IconList.Images.SetKeyName(487, "068-sign-language.png");
            this.IconList.Images.SetKeyName(488, "068-ux.png");
            this.IconList.Images.SetKeyName(489, "069-branch-1.png");
            this.IconList.Images.SetKeyName(490, "069-cancer-cell.png");
            this.IconList.Images.SetKeyName(491, "069-knowledge.png");
            this.IconList.Images.SetKeyName(492, "069-medicine.png");
            this.IconList.Images.SetKeyName(493, "069-radioactive.png");
            this.IconList.Images.SetKeyName(494, "069-security.png");
            this.IconList.Images.SetKeyName(495, "070-cancer-cell-1.png");
            this.IconList.Images.SetKeyName(496, "070-circuit.png");
            this.IconList.Images.SetKeyName(497, "070-computer.png");
            this.IconList.Images.SetKeyName(498, "070-no-internet.png");
            this.IconList.Images.SetKeyName(499, "070-waste-water.png");
            this.IconList.Images.SetKeyName(500, "070-water.png");
            this.IconList.Images.SetKeyName(501, "071-artificial-intelligence-3.png");
            this.IconList.Images.SetKeyName(502, "071-cancer-cell-2.png");
            this.IconList.Images.SetKeyName(503, "071-light-bulb.png");
            this.IconList.Images.SetKeyName(504, "071-microchip.png");
            this.IconList.Images.SetKeyName(505, "071-no-internet-1.png");
            this.IconList.Images.SetKeyName(506, "071-waste-water-1.png");
            this.IconList.Images.SetKeyName(507, "072-atom.png");
            this.IconList.Images.SetKeyName(508, "072-support.png");
            this.IconList.Images.SetKeyName(509, "072-tower.png");
            this.IconList.Images.SetKeyName(510, "072-waste-1.png");
            this.IconList.Images.SetKeyName(511, "072-water-drops.png");
            this.IconList.Images.SetKeyName(512, "073-cpu.png");
            this.IconList.Images.SetKeyName(513, "073-gateway-1.png");
            this.IconList.Images.SetKeyName(514, "073-nanomedicine.png");
            this.IconList.Images.SetKeyName(515, "073-synthetic-food.png");
            this.IconList.Images.SetKeyName(516, "073-waste-2.png");
            this.IconList.Images.SetKeyName(517, "074-blood-cell.png");
            this.IconList.Images.SetKeyName(518, "074-brain.png");
            this.IconList.Images.SetKeyName(519, "074-crutches.png");
            this.IconList.Images.SetKeyName(520, "074-eye-scan.png");
            this.IconList.Images.SetKeyName(521, "074-waste-water-2.png");
            this.IconList.Images.SetKeyName(522, "075-bacteria.png");
            this.IconList.Images.SetKeyName(523, "075-chemical-reaction.png");
            this.IconList.Images.SetKeyName(524, "075-diamond.png");
            this.IconList.Images.SetKeyName(525, "075-led-light-1.png");
            this.IconList.Images.SetKeyName(526, "075-nanoparticle.png");
            this.IconList.Images.SetKeyName(527, "076-blood-cell-1.png");
            this.IconList.Images.SetKeyName(528, "076-brain-1.png");
            this.IconList.Images.SetKeyName(529, "076-formula.png");
            this.IconList.Images.SetKeyName(530, "076-neon.png");
            this.IconList.Images.SetKeyName(531, "076-smart-clothing.png");
            this.IconList.Images.SetKeyName(532, "077-bacteria-1.png");
            this.IconList.Images.SetKeyName(533, "077-chemical-reaction.png");
            this.IconList.Images.SetKeyName(534, "077-contactless-1.png");
            this.IconList.Images.SetKeyName(535, "077-medical-research.png");
            this.IconList.Images.SetKeyName(536, "077-science.png");
            this.IconList.Images.SetKeyName(537, "078-air-filter-1.png");
            this.IconList.Images.SetKeyName(538, "078-cell.png");
            this.IconList.Images.SetKeyName(539, "078-microscope-1.png");
            this.IconList.Images.SetKeyName(540, "078-robotic-arm.png");
            this.IconList.Images.SetKeyName(541, "078-scientist.png");
            this.IconList.Images.SetKeyName(542, "079-bacteria-2.png");
            this.IconList.Images.SetKeyName(543, "079-compound.png");
            this.IconList.Images.SetKeyName(544, "079-counter.png");
            this.IconList.Images.SetKeyName(545, "079-heart-rate.png");
            this.IconList.Images.SetKeyName(546, "079-surgery.png");
            this.IconList.Images.SetKeyName(547, "080-blood-cells-1.png");
            this.IconList.Images.SetKeyName(548, "080-drone.png");
            this.IconList.Images.SetKeyName(549, "080-robot.png");
            this.IconList.Images.SetKeyName(550, "080-test-tubes.png");
            this.IconList.Images.SetKeyName(551, "080-undefined.png");
            this.IconList.Images.SetKeyName(552, "081-chip-2.png");
            this.IconList.Images.SetKeyName(553, "081-formula-1.png");
            this.IconList.Images.SetKeyName(554, "081-hand-up.png");
            this.IconList.Images.SetKeyName(555, "081-research.png");
            this.IconList.Images.SetKeyName(556, "081-virus.png");
            this.IconList.Images.SetKeyName(557, "082-blood-cells-2.png");
            this.IconList.Images.SetKeyName(558, "082-evolution.png");
            this.IconList.Images.SetKeyName(559, "082-laptop.png");
            this.IconList.Images.SetKeyName(560, "082-smart-key.png");
            this.IconList.Images.SetKeyName(561, "082-toxic.png");
            this.IconList.Images.SetKeyName(562, "083-blood-cells-3.png");
            this.IconList.Images.SetKeyName(563, "083-building.png");
            this.IconList.Images.SetKeyName(564, "083-eco-light.png");
            this.IconList.Images.SetKeyName(565, "083-molecular.png");
            this.IconList.Images.SetKeyName(566, "083-web-programming.png");
            this.IconList.Images.SetKeyName(567, "084-antibody.png");
            this.IconList.Images.SetKeyName(568, "084-battery.png");
            this.IconList.Images.SetKeyName(569, "084-beakers.png");
            this.IconList.Images.SetKeyName(570, "084-sugar-cane.png");
            this.IconList.Images.SetKeyName(571, "084-target.png");
            this.IconList.Images.SetKeyName(572, "085-binary-code.png");
            this.IconList.Images.SetKeyName(573, "085-flask.png");
            this.IconList.Images.SetKeyName(574, "085-molecule-1.png");
            this.IconList.Images.SetKeyName(575, "085-tulip.png");
            this.IconList.Images.SetKeyName(576, "085-typing.png");
            this.IconList.Images.SetKeyName(577, "086-cell-1.png");
            this.IconList.Images.SetKeyName(578, "086-formula-2.png");
            this.IconList.Images.SetKeyName(579, "086-lavender.png");
            this.IconList.Images.SetKeyName(580, "086-round-chart.png");
            this.IconList.Images.SetKeyName(581, "086-wrench.png");
            this.IconList.Images.SetKeyName(582, "087-battery.png");
            this.IconList.Images.SetKeyName(583, "087-cell-2.png");
            this.IconList.Images.SetKeyName(584, "087-circuit-1.png");
            this.IconList.Images.SetKeyName(585, "087-laboratory.png");
            this.IconList.Images.SetKeyName(586, "087-turbine.png");
            this.IconList.Images.SetKeyName(587, "088-aroma.png");
            this.IconList.Images.SetKeyName(588, "088-barrel.png");
            this.IconList.Images.SetKeyName(589, "088-computer-1.png");
            this.IconList.Images.SetKeyName(590, "088-music.png");
            this.IconList.Images.SetKeyName(591, "088-nanometer.png");
            this.IconList.Images.SetKeyName(592, "089-blueprint.png");
            this.IconList.Images.SetKeyName(593, "089-communications.png");
            this.IconList.Images.SetKeyName(594, "089-hardware-1.png");
            this.IconList.Images.SetKeyName(595, "089-medical-research.png");
            this.IconList.Images.SetKeyName(596, "089-tram.png");
            this.IconList.Images.SetKeyName(597, "090-algae.png");
            this.IconList.Images.SetKeyName(598, "090-binary-code-1.png");
            this.IconList.Images.SetKeyName(599, "090-medicines.png");
            this.IconList.Images.SetKeyName(600, "090-nontoxic.png");
            this.IconList.Images.SetKeyName(601, "090-rocket.png");
            this.IconList.Images.SetKeyName(602, "091-conveyor.png");
            this.IconList.Images.SetKeyName(603, "091-electrocardiogram.png");
            this.IconList.Images.SetKeyName(604, "091-prescription.png");
            this.IconList.Images.SetKeyName(605, "091-ship-wheel.png");
            this.IconList.Images.SetKeyName(606, "092-agronomy.png");
            this.IconList.Images.SetKeyName(607, "092-brain.png");
            this.IconList.Images.SetKeyName(608, "092-dna.png");
            this.IconList.Images.SetKeyName(609, "092-fraud.png");
            this.IconList.Images.SetKeyName(610, "093-cloud-computing.png");
            this.IconList.Images.SetKeyName(611, "093-dj-mixer.png");
            this.IconList.Images.SetKeyName(612, "093-injection.png");
            this.IconList.Images.SetKeyName(613, "093-schedule.png");
            this.IconList.Images.SetKeyName(614, "094-density.png");
            this.IconList.Images.SetKeyName(615, "094-doctor.png");
            this.IconList.Images.SetKeyName(616, "094-medicine.png");
            this.IconList.Images.SetKeyName(617, "094-microprocessor.png");
            this.IconList.Images.SetKeyName(618, "095-atom-4.png");
            this.IconList.Images.SetKeyName(619, "095-chutney.png");
            this.IconList.Images.SetKeyName(620, "095-flower.png");
            this.IconList.Images.SetKeyName(621, "095-water.png");
            this.IconList.Images.SetKeyName(622, "096-atom-5.png");
            this.IconList.Images.SetKeyName(623, "096-blood-bag.png");
            this.IconList.Images.SetKeyName(624, "096-clef.png");
            this.IconList.Images.SetKeyName(625, "096-defrost-2.png");
            this.IconList.Images.SetKeyName(626, "097-cheese.png");
            this.IconList.Images.SetKeyName(627, "097-difficulty-breathing.png");
            this.IconList.Images.SetKeyName(628, "097-sink.png");
            this.IconList.Images.SetKeyName(629, "097-syringe.png");
            this.IconList.Images.SetKeyName(630, "098-injection.png");
            this.IconList.Images.SetKeyName(631, "098-transfusion.png");
            this.IconList.Images.SetKeyName(632, "099-injection-1.png");
            this.IconList.Images.SetKeyName(633, "099-pharmacist.png");
            this.IconList.Images.SetKeyName(634, "099-thunderstorm.png");
            this.IconList.Images.SetKeyName(635, "099-tree.png");
            this.IconList.Images.SetKeyName(636, "100-biodegradable.png");
            this.IconList.Images.SetKeyName(637, "100-earth-1.png");
            this.IconList.Images.SetKeyName(638, "100-stethoscope.png");
            this.IconList.Images.SetKeyName(639, "100-vaccination.png");
            this.IconList.Images.SetKeyName(640, "101-bobbin.png");
            this.IconList.Images.SetKeyName(641, "101-coverall.png");
            this.IconList.Images.SetKeyName(642, "101-marijuana.png");
            this.IconList.Images.SetKeyName(643, "101-medical-tools.png");
            this.IconList.Images.SetKeyName(644, "102-cell.png");
            this.IconList.Images.SetKeyName(645, "102-health-check.png");
            this.IconList.Images.SetKeyName(646, "102-palm-oil.png");
            this.IconList.Images.SetKeyName(647, "102-radar.png");
            this.IconList.Images.SetKeyName(648, "103-insemination.png");
            this.IconList.Images.SetKeyName(649, "103-jackhammer.png");
            this.IconList.Images.SetKeyName(650, "103-wheat.png");
            this.IconList.Images.SetKeyName(651, "103-x-ray.png");
            this.IconList.Images.SetKeyName(652, "104-clock.png");
            this.IconList.Images.SetKeyName(653, "104-ecosystem.png");
            this.IconList.Images.SetKeyName(654, "104-examination.png");
            this.IconList.Images.SetKeyName(655, "104-experiment.png");
            this.IconList.Images.SetKeyName(656, "105-injection-2.png");
            this.IconList.Images.SetKeyName(657, "105-joint.png");
            this.IconList.Images.SetKeyName(658, "105-people.png");
            this.IconList.Images.SetKeyName(659, "105-stethoscope-1.png");
            this.IconList.Images.SetKeyName(660, "106-gavel.png");
            this.IconList.Images.SetKeyName(661, "106-planets.png");
            this.IconList.Images.SetKeyName(662, "106-plant-1.png");
            this.IconList.Images.SetKeyName(663, "106-vaccine.png");
            this.IconList.Images.SetKeyName(664, "107-aid.png");
            this.IconList.Images.SetKeyName(665, "107-branch-2.png");
            this.IconList.Images.SetKeyName(666, "107-law.png");
            this.IconList.Images.SetKeyName(667, "107-meteorite.png");
            this.IconList.Images.SetKeyName(668, "108-consultation.png");
            this.IconList.Images.SetKeyName(669, "108-gateway-2.png");
            this.IconList.Images.SetKeyName(670, "108-handcuffs.png");
            this.IconList.Images.SetKeyName(671, "108-video-link.png");
            this.IconList.Images.SetKeyName(672, "109-air-filter-2.png");
            this.IconList.Images.SetKeyName(673, "109-doctor.png");
            this.IconList.Images.SetKeyName(674, "109-job-search.png");
            this.IconList.Images.SetKeyName(675, "109-prison.png");
            this.IconList.Images.SetKeyName(676, "110-biology.png");
            this.IconList.Images.SetKeyName(677, "110-doctor-1.png");
            this.IconList.Images.SetKeyName(678, "110-electric-motor.png");
            this.IconList.Images.SetKeyName(679, "110-molecules.png");
            this.IconList.Images.SetKeyName(680, "111-biohazard.png");
            this.IconList.Images.SetKeyName(681, "111-diagnosis.png");
            this.IconList.Images.SetKeyName(682, "111-equalizer.png");
            this.IconList.Images.SetKeyName(683, "111-turbine.png");
            this.IconList.Images.SetKeyName(684, "112-artificial-intelligence.png");
            this.IconList.Images.SetKeyName(685, "112-fingerprint-scan.png");
            this.IconList.Images.SetKeyName(686, "112-medical-team.png");
            this.IconList.Images.SetKeyName(687, "112-wind-turbine.png");
            this.IconList.Images.SetKeyName(688, "113-industrial-robot.png");
            this.IconList.Images.SetKeyName(689, "113-pills.png");
            this.IconList.Images.SetKeyName(690, "113-stethoscope-2.png");
            this.IconList.Images.SetKeyName(691, "113-wind-turbine-1.png");
            this.IconList.Images.SetKeyName(692, "114-bioengineering.png");
            this.IconList.Images.SetKeyName(693, "114-biomechanics.png");
            this.IconList.Images.SetKeyName(694, "114-monitor.png");
            this.IconList.Images.SetKeyName(695, "114-vial.png");
            this.IconList.Images.SetKeyName(696, "115-coronavirus.png");
            this.IconList.Images.SetKeyName(697, "115-dropper.png");
            this.IconList.Images.SetKeyName(698, "115-gloves.png");
            this.IconList.Images.SetKeyName(699, "115-molecule.png");
            this.IconList.Images.SetKeyName(700, "116-embryo.png");
            this.IconList.Images.SetKeyName(701, "116-fire.png");
            this.IconList.Images.SetKeyName(702, "116-pills.png");
            this.IconList.Images.SetKeyName(703, "116-vaccination.png");
            this.IconList.Images.SetKeyName(704, "117-cardiogram.png");
            this.IconList.Images.SetKeyName(705, "117-helix.png");
            this.IconList.Images.SetKeyName(706, "117-insemination.png");
            this.IconList.Images.SetKeyName(707, "118-medicament.png");
            this.IconList.Images.SetKeyName(708, "118-operating-room.png");
            this.IconList.Images.SetKeyName(709, "118-pc.png");
            this.IconList.Images.SetKeyName(710, "118-sandglass.png");
            this.IconList.Images.SetKeyName(711, "119-scroll.png");
            this.IconList.Images.SetKeyName(712, "119-testing.png");
            this.IconList.Images.SetKeyName(713, "119-vaccine-1.png");
            this.IconList.Images.SetKeyName(714, "119-virus-1.png");
            this.IconList.Images.SetKeyName(715, "120-clinical-psychology.png");
            this.IconList.Images.SetKeyName(716, "120-genetics.png");
            this.IconList.Images.SetKeyName(717, "120-synthetic-food.png");
            this.IconList.Images.SetKeyName(718, "120-workplace.png");
            this.IconList.Images.SetKeyName(719, "121-bacteria.png");
            this.IconList.Images.SetKeyName(720, "121-heartbeat.png");
            this.IconList.Images.SetKeyName(721, "121-laboratory.png");
            this.IconList.Images.SetKeyName(722, "121-space.png");
            this.IconList.Images.SetKeyName(723, "122-bar-chart.png");
            this.IconList.Images.SetKeyName(724, "122-brain.png");
            this.IconList.Images.SetKeyName(725, "122-centrifuge.png");
            this.IconList.Images.SetKeyName(726, "122-virus-2.png");
            this.IconList.Images.SetKeyName(727, "123-gear-2.png");
            this.IconList.Images.SetKeyName(728, "123-gmo.png");
            this.IconList.Images.SetKeyName(729, "123-medicament.png");
            this.IconList.Images.SetKeyName(730, "123-psychology.png");
            this.IconList.Images.SetKeyName(731, "124-mental-health.png");
            this.IconList.Images.SetKeyName(732, "124-patent.png");
            this.IconList.Images.SetKeyName(733, "124-vaccine.png");
            this.IconList.Images.SetKeyName(734, "125-annual-report.png");
            this.IconList.Images.SetKeyName(735, "125-brain-1.png");
            this.IconList.Images.SetKeyName(736, "125-factory.png");
            this.IconList.Images.SetKeyName(737, "126-biomechanics.png");
            this.IconList.Images.SetKeyName(738, "126-copywriting.png");
            this.IconList.Images.SetKeyName(739, "126-overthinking.png");
            this.IconList.Images.SetKeyName(740, "127-bioenergy.png");
            this.IconList.Images.SetKeyName(741, "127-brain-2.png");
            this.IconList.Images.SetKeyName(742, "127-skills.png");
            this.IconList.Images.SetKeyName(743, "128-afternoon.png");
            this.IconList.Images.SetKeyName(744, "128-biorobot.png");
            this.IconList.Images.SetKeyName(745, "128-brain-3.png");
            this.IconList.Images.SetKeyName(746, "129-electronic-circuit.png");
            this.IconList.Images.SetKeyName(747, "129-incubator.png");
            this.IconList.Images.SetKeyName(748, "129-rain.png");
            this.IconList.Images.SetKeyName(749, "130-mushroom.png");
            this.IconList.Images.SetKeyName(750, "130-plant-2.png");
            this.IconList.Images.SetKeyName(751, "130-shopping-cart.png");
            this.IconList.Images.SetKeyName(752, "131-cloning.png");
            this.IconList.Images.SetKeyName(753, "131-genes.png");
            this.IconList.Images.SetKeyName(754, "131-tree.png");
            this.IconList.Images.SetKeyName(755, "132-sprout.png");
            this.IconList.Images.SetKeyName(756, "132-waste.png");
            this.IconList.Images.SetKeyName(757, "132-window.png");
            this.IconList.Images.SetKeyName(758, "133-ecologism.png");
            this.IconList.Images.SetKeyName(759, "133-green.png");
            this.IconList.Images.SetKeyName(760, "133-pills-1.png");
            this.IconList.Images.SetKeyName(761, "134-in-vitro.png");
            this.IconList.Images.SetKeyName(762, "134-nightmare.png");
            this.IconList.Images.SetKeyName(763, "134-wheat.png");
            this.IconList.Images.SetKeyName(764, "135-beet.png");
            this.IconList.Images.SetKeyName(765, "135-gender.png");
            this.IconList.Images.SetKeyName(766, "135-mitosis.png");
            this.IconList.Images.SetKeyName(767, "136-medical-report.png");
            this.IconList.Images.SetKeyName(768, "136-nanorobot.png");
            this.IconList.Images.SetKeyName(769, "136-nut.png");
            this.IconList.Images.SetKeyName(770, "137-biopsy.png");
            this.IconList.Images.SetKeyName(771, "137-conservation.png");
            this.IconList.Images.SetKeyName(772, "137-microscope.png");
            this.IconList.Images.SetKeyName(773, "138-mouse.png");
            this.IconList.Images.SetKeyName(774, "138-seeds.png");
            this.IconList.Images.SetKeyName(775, "138-theater-1.png");
            this.IconList.Images.SetKeyName(776, "139-molecule.png");
            this.IconList.Images.SetKeyName(777, "139-research.png");
            this.IconList.Images.SetKeyName(778, "139-social-network.png");
            this.IconList.Images.SetKeyName(779, "140-beakers.png");
            this.IconList.Images.SetKeyName(780, "140-earth.png");
            this.IconList.Images.SetKeyName(781, "140-time-management.png");
            this.IconList.Images.SetKeyName(782, "141-discount.png");
            this.IconList.Images.SetKeyName(783, "141-hybrid.png");
            this.IconList.Images.SetKeyName(784, "141-research-1.png");
            this.IconList.Images.SetKeyName(785, "142-brain-4.png");
            this.IconList.Images.SetKeyName(786, "142-conveyor-1.png");
            this.IconList.Images.SetKeyName(787, "142-spores.png");
            this.IconList.Images.SetKeyName(788, "143-gmo.png");
            this.IconList.Images.SetKeyName(789, "143-police.png");
            this.IconList.Images.SetKeyName(790, "143-tools.png");
            this.IconList.Images.SetKeyName(791, "144-bio-sensor.png");
            this.IconList.Images.SetKeyName(792, "144-handcuffs.png");
            this.IconList.Images.SetKeyName(793, "144-pencil.png");
            this.IconList.Images.SetKeyName(794, "145-bioreactor.png");
            this.IconList.Images.SetKeyName(795, "145-book.png");
            this.IconList.Images.SetKeyName(796, "145-flasher.png");
            this.IconList.Images.SetKeyName(797, "146-injection.png");
            this.IconList.Images.SetKeyName(798, "146-pc.png");
            this.IconList.Images.SetKeyName(799, "146-shield.png");
            this.IconList.Images.SetKeyName(800, "147-astronaut.png");
            this.IconList.Images.SetKeyName(801, "147-formula.png");
            this.IconList.Images.SetKeyName(802, "147-satellite.png");
            this.IconList.Images.SetKeyName(803, "148-astronaut-1.png");
            this.IconList.Images.SetKeyName(804, "148-biotechnology.png");
            this.IconList.Images.SetKeyName(805, "148-scroll-1.png");
            this.IconList.Images.SetKeyName(806, "149-art.png");
            this.IconList.Images.SetKeyName(807, "149-dna.png");
            this.IconList.Images.SetKeyName(808, "149-project.png");
            this.IconList.Images.SetKeyName(809, "150-rocket.png");
            this.IconList.Images.SetKeyName(810, "150-surgery-robot.png");
            this.IconList.Images.SetKeyName(811, "151-rocket-1.png");
            this.IconList.Images.SetKeyName(812, "151-virus.png");
            this.IconList.Images.SetKeyName(813, "152-blood.png");
            this.IconList.Images.SetKeyName(814, "152-economy.png");
            this.IconList.Images.SetKeyName(815, "153-atmosphere.png");
            this.IconList.Images.SetKeyName(816, "153-chemicals.png");
            this.IconList.Images.SetKeyName(817, "154-meteorology.png");
            this.IconList.Images.SetKeyName(818, "154-research.png");
            this.IconList.Images.SetKeyName(819, "155-chemistry.png");
            this.IconList.Images.SetKeyName(820, "155-science-1.png");
            this.IconList.Images.SetKeyName(821, "156-bacteria.png");
            this.IconList.Images.SetKeyName(822, "156-compass-1.png");
            this.IconList.Images.SetKeyName(823, "157-artificial-heart.png");
            this.IconList.Images.SetKeyName(824, "157-tropical.png");
            this.IconList.Images.SetKeyName(825, "158-antibody.png");
            this.IconList.Images.SetKeyName(826, "158-black-hole.png");
            this.IconList.Images.SetKeyName(827, "159-dna-1.png");
            this.IconList.Images.SetKeyName(828, "159-law-book.png");
            this.IconList.Images.SetKeyName(829, "160-fish.png");
            this.IconList.Images.SetKeyName(830, "160-gene.png");
            this.IconList.Images.SetKeyName(831, "161-bee.png");
            this.IconList.Images.SetKeyName(832, "161-helix.png");
            this.IconList.Images.SetKeyName(833, "162-algorithm.png");
            this.IconList.Images.SetKeyName(834, "162-nanotechnology.png");
            this.IconList.Images.SetKeyName(835, "163-design.png");
            this.IconList.Images.SetKeyName(836, "163-dna-2.png");
            this.IconList.Images.SetKeyName(837, "164-gear-3.png");
            this.IconList.Images.SetKeyName(838, "164-kinship.png");
            this.IconList.Images.SetKeyName(839, "165-chromosome.png");
            this.IconList.Images.SetKeyName(840, "165-lightbulb.png");
            this.IconList.Images.SetKeyName(841, "166-dna-3.png");
            this.IconList.Images.SetKeyName(842, "166-gears.png");
            this.IconList.Images.SetKeyName(843, "167-family-tree.png");
            this.IconList.Images.SetKeyName(844, "167-scheme.png");
            this.IconList.Images.SetKeyName(845, "168-monitor.png");
            this.IconList.Images.SetKeyName(846, "168-thinking.png");
            this.IconList.Images.SetKeyName(847, "169-genetic-modification.png");
            this.IconList.Images.SetKeyName(848, "169-layout.png");
            this.IconList.Images.SetKeyName(849, "170-dna-4.png");
            this.IconList.Images.SetKeyName(850, "170-wind-rose.png");
            this.IconList.Images.SetKeyName(851, "171-destination.png");
            this.IconList.Images.SetKeyName(852, "171-dna-test.png");
            this.IconList.Images.SetKeyName(853, "172-destination-1.png");
            this.IconList.Images.SetKeyName(854, "172-dna-5.png");
            this.IconList.Images.SetKeyName(855, "173-destination-2.png");
            this.IconList.Images.SetKeyName(856, "173-safe-box-1.png");
            this.IconList.Images.SetKeyName(857, "174-plant-3.png");
            this.IconList.Images.SetKeyName(858, "174-zeus.png");
            this.IconList.Images.SetKeyName(859, "175-pharmacy.png");
            this.IconList.Images.SetKeyName(860, "175-scientist.png");
            this.IconList.Images.SetKeyName(861, "176-chromosomes.png");
            this.IconList.Images.SetKeyName(862, "176-lyre.png");
            this.IconList.Images.SetKeyName(863, "177-notebook.png");
            this.IconList.Images.SetKeyName(864, "177-search.png");
            this.IconList.Images.SetKeyName(865, "178-computer.png");
            this.IconList.Images.SetKeyName(866, "178-link.png");
            this.IconList.Images.SetKeyName(867, "179-dna-test-1.png");
            this.IconList.Images.SetKeyName(868, "179-wind.png");
            this.IconList.Images.SetKeyName(869, "180-eclipse.png");
            this.IconList.Images.SetKeyName(870, "180-project.png");
            this.IconList.Images.SetKeyName(871, "181-koi.png");
            this.IconList.Images.SetKeyName(872, "181-research-1.png");
            this.IconList.Images.SetKeyName(873, "182-hair.png");
            this.IconList.Images.SetKeyName(874, "183-drop.png");
            this.IconList.Images.SetKeyName(875, "183-search-1.png");
            this.IconList.Images.SetKeyName(876, "184-test-tubes.png");
            this.IconList.Images.SetKeyName(877, "184-virus-1.png");
            this.IconList.Images.SetKeyName(878, "185-heart-rate-1.png");
            this.IconList.Images.SetKeyName(879, "185-test-tubes.png");
            this.IconList.Images.SetKeyName(880, "186-gears-1.png");
            this.IconList.Images.SetKeyName(881, "186-mitochondria.png");
            this.IconList.Images.SetKeyName(882, "187-dna-test-2.png");
            this.IconList.Images.SetKeyName(883, "187-fish-tank.png");
            this.IconList.Images.SetKeyName(884, "188-line-chart-1.png");
            this.IconList.Images.SetKeyName(885, "188-scientist-1.png");
            this.IconList.Images.SetKeyName(886, "189-blood-sample.png");
            this.IconList.Images.SetKeyName(887, "189-smog.png");
            this.IconList.Images.SetKeyName(888, "190-bacteria-1.png");
            this.IconList.Images.SetKeyName(889, "190-settings.png");
            this.IconList.Images.SetKeyName(890, "191-dna-6.png");
            this.IconList.Images.SetKeyName(891, "191-graph.png");
            this.IconList.Images.SetKeyName(892, "192-animal.png");
            this.IconList.Images.SetKeyName(893, "192-genetics.png");
            this.IconList.Images.SetKeyName(894, "193-dna-7.png");
            this.IconList.Images.SetKeyName(895, "193-satellite-1.png");
            this.IconList.Images.SetKeyName(896, "194-chromosome-1.png");
            this.IconList.Images.SetKeyName(897, "194-velvet-ant.png");
            this.IconList.Images.SetKeyName(898, "195-feather-of-maat.png");
            this.IconList.Images.SetKeyName(899, "195-formula-1.png");
            this.IconList.Images.SetKeyName(900, "196-injection-1.png");
            this.IconList.Images.SetKeyName(901, "196-treble-clef.png");
            this.IconList.Images.SetKeyName(902, "197-daydream-elements.png");
            this.IconList.Images.SetKeyName(903, "197-dna-test-3.png");
            this.IconList.Images.SetKeyName(904, "198-results.png");
            this.IconList.Images.SetKeyName(905, "198-vaccine-1.png");
            this.IconList.Images.SetKeyName(906, "199-mitochondria-1.png");
            this.IconList.Images.SetKeyName(907, "199-music-sheet.png");
            this.IconList.Images.SetKeyName(908, "200-3d-design.png");
            this.IconList.Images.SetKeyName(909, "200-nail.png");
            this.IconList.Images.SetKeyName(910, "201-crab.png");
            this.IconList.Images.SetKeyName(911, "201-medicine.png");
            this.IconList.Images.SetKeyName(912, "202-book-1.png");
            this.IconList.Images.SetKeyName(913, "202-mutation.png");
            this.IconList.Images.SetKeyName(914, "203-flask.png");
            this.IconList.Images.SetKeyName(915, "203-observatory.png");
            this.IconList.Images.SetKeyName(916, "204-artificial-intelligence.png");
            this.IconList.Images.SetKeyName(917, "204-blood-sample-1.png");
            this.IconList.Images.SetKeyName(918, "205-gene.png");
            this.IconList.Images.SetKeyName(919, "205-genetics-1.png");
            this.IconList.Images.SetKeyName(920, "206-bionic-organ.png");
            this.IconList.Images.SetKeyName(921, "206-test-tube.png");
            this.IconList.Images.SetKeyName(922, "207-biotechnology.png");
            this.IconList.Images.SetKeyName(923, "207-dna-8.png");
            this.IconList.Images.SetKeyName(924, "208-mitochondria-2.png");
            this.IconList.Images.SetKeyName(925, "208-robotic-leg.png");
            this.IconList.Images.SetKeyName(926, "209-microscope-1.png");
            this.IconList.Images.SetKeyName(927, "209-smart-lens.png");
            this.IconList.Images.SetKeyName(928, "210-smart-city.png");
            this.IconList.Images.SetKeyName(929, "210-tongue-cleaner.png");
            this.IconList.Images.SetKeyName(930, "211-pipette.png");
            this.IconList.Images.SetKeyName(931, "211-robotic-hand.png");
            this.IconList.Images.SetKeyName(932, "212-mobile-net.png");
            this.IconList.Images.SetKeyName(933, "212-scientist-2.png");
            this.IconList.Images.SetKeyName(934, "213-medical-app.png");
            this.IconList.Images.SetKeyName(935, "213-no-gmo.png");
            this.IconList.Images.SetKeyName(936, "214-cotton-swab.png");
            this.IconList.Images.SetKeyName(937, "214-dna-9.png");
            this.IconList.Images.SetKeyName(938, "215-dna-10.png");
            this.IconList.Images.SetKeyName(939, "215-vaccine-2.png");
            this.IconList.Images.SetKeyName(940, "216-biodiversity.png");
            this.IconList.Images.SetKeyName(941, "217-sakura.png");
            this.IconList.Images.SetKeyName(942, "217-test-tube-1.png");
            this.IconList.Images.SetKeyName(943, "218-book-2.png");
            this.IconList.Images.SetKeyName(944, "218-cloning-1.png");
            this.IconList.Images.SetKeyName(945, "219-barrier.png");
            this.IconList.Images.SetKeyName(946, "219-compound.png");
            this.IconList.Images.SetKeyName(947, "220-bee-1.png");
            this.IconList.Images.SetKeyName(948, "220-nanomachine.png");
            this.IconList.Images.SetKeyName(949, "221-atom.png");
            this.IconList.Images.SetKeyName(950, "221-patient.png");
            this.IconList.Images.SetKeyName(951, "222-3d-printer.png");
            this.IconList.Images.SetKeyName(952, "222-medical-laboratory.png");
            this.IconList.Images.SetKeyName(953, "223-chemistry-1.png");
            this.IconList.Images.SetKeyName(954, "224-artificial-intelligence-1.png");
            this.IconList.Images.SetKeyName(955, "224-flask-1.png");
            this.IconList.Images.SetKeyName(956, "225-data-storage.png");
            this.IconList.Images.SetKeyName(957, "225-scientist-3.png");
            this.IconList.Images.SetKeyName(958, "226-formula-2.png");
            this.IconList.Images.SetKeyName(959, "226-pc-1.png");
            this.IconList.Images.SetKeyName(960, "227-atom-1.png");
            this.IconList.Images.SetKeyName(961, "227-gears-2.png");
            this.IconList.Images.SetKeyName(962, "228-link-1.png");
            this.IconList.Images.SetKeyName(963, "228-molecule-1.png");
            this.IconList.Images.SetKeyName(964, "229-laboratory-1.png");
            this.IconList.Images.SetKeyName(965, "229-manipulator.png");
            this.IconList.Images.SetKeyName(966, "230-experiment.png");
            this.IconList.Images.SetKeyName(967, "230-personal-computer.png");
            this.IconList.Images.SetKeyName(968, "231-chemistry-2.png");
            this.IconList.Images.SetKeyName(969, "231-gear-4.png");
            this.IconList.Images.SetKeyName(970, "232-chemistry-3.png");
            this.IconList.Images.SetKeyName(971, "232-remote-control.png");
            this.IconList.Images.SetKeyName(972, "233-lunar-module.png");
            this.IconList.Images.SetKeyName(973, "233-physics.png");
            this.IconList.Images.SetKeyName(974, "234-dropper-1.png");
            this.IconList.Images.SetKeyName(975, "234-robotic-hand-1.png");
            this.IconList.Images.SetKeyName(976, "235-circuit.png");
            this.IconList.Images.SetKeyName(977, "235-test-tubes-1.png");
            this.IconList.Images.SetKeyName(978, "236-chemical-reaction.png");
            this.IconList.Images.SetKeyName(979, "237-science.png");
            this.IconList.Images.SetKeyName(980, "237-server.png");
            this.IconList.Images.SetKeyName(981, "238-signal-tower.png");
            this.IconList.Images.SetKeyName(982, "238-test-tubes-2.png");
            this.IconList.Images.SetKeyName(983, "239-material.png");
            this.IconList.Images.SetKeyName(984, "239-walkie-talkie.png");
            this.IconList.Images.SetKeyName(985, "240-book-1.png");
            this.IconList.Images.SetKeyName(986, "240-medicines.png");
            this.IconList.Images.SetKeyName(987, "241-garden.png");
            this.IconList.Images.SetKeyName(988, "241-test-tube-2.png");
            this.IconList.Images.SetKeyName(989, "242-blackboard.png");
            this.IconList.Images.SetKeyName(990, "242-brain-1.png");
            this.IconList.Images.SetKeyName(991, "243-dna.png");
            this.IconList.Images.SetKeyName(992, "243-substance.png");
            this.IconList.Images.SetKeyName(993, "244-mold.png");
            this.IconList.Images.SetKeyName(994, "244-molecule.png");
            this.IconList.Images.SetKeyName(995, "245-loupe-1.png");
            this.IconList.Images.SetKeyName(996, "245-periodic-table.png");
            this.IconList.Images.SetKeyName(997, "246-preservative.png");
            this.IconList.Images.SetKeyName(998, "246-question.png");
            this.IconList.Images.SetKeyName(999, "247-food.png");
            this.IconList.Images.SetKeyName(1000, "247-pc-2.png");
            this.IconList.Images.SetKeyName(1001, "248-beakers-1.png");
            this.IconList.Images.SetKeyName(1002, "248-detector.png");
            this.IconList.Images.SetKeyName(1003, "249-binary-code-1.png");
            this.IconList.Images.SetKeyName(1004, "249-science-1.png");
            this.IconList.Images.SetKeyName(1005, "250-molecule-2.png");
            this.IconList.Images.SetKeyName(1006, "250-thinking-1.png");
            this.IconList.Images.SetKeyName(1007, "251-alphabet.png");
            this.IconList.Images.SetKeyName(1008, "251-chemistry-4.png");
            this.IconList.Images.SetKeyName(1009, "252-botany.png");
            this.IconList.Images.SetKeyName(1010, "252-smart-key.png");
            this.IconList.Images.SetKeyName(1011, "253-microscope-2.png");
            this.IconList.Images.SetKeyName(1012, "253-punch.png");
            this.IconList.Images.SetKeyName(1013, "254-mortarboard.png");
            this.IconList.Images.SetKeyName(1014, "254-robot.png");
            this.IconList.Images.SetKeyName(1015, "255-h2o.png");
            this.IconList.Images.SetKeyName(1016, "255-silverfish.png");
            this.IconList.Images.SetKeyName(1017, "256-sulphite.png");
            this.IconList.Images.SetKeyName(1018, "biohazard.png");
            this.IconList.Images.SetKeyName(1019, "drone.png");
            this.IconList.Images.SetKeyName(1020, "earth.png");
            this.IconList.Images.SetKeyName(1021, "embryo.png");
            this.IconList.Images.SetKeyName(1022, "map.png");
            this.IconList.Images.SetKeyName(1023, "medicine-128.png");
            // 
            // Panels
            // 
            this.Panels.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.Panels.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Panels.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.Panels.Location = new System.Drawing.Point(0, 24);
            this.Panels.Name = "Panels";
            // 
            // Panels.Panel1
            // 
            this.Panels.Panel1.Controls.Add(this.ListCategories);
            // 
            // Panels.Panel2
            // 
            this.Panels.Panel2.Controls.Add(this.ListViewTechs);
            this.Panels.Size = new System.Drawing.Size(784, 537);
            this.Panels.SplitterDistance = 222;
            this.Panels.TabIndex = 3;
            // 
            // ListCategories
            // 
            this.ListCategories.ContextMenuStrip = this.MenuCategoriesContext;
            this.ListCategories.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ListCategories.HideSelection = false;
            this.ListCategories.LargeImageList = this.CategoryIcons;
            this.ListCategories.Location = new System.Drawing.Point(0, 0);
            this.ListCategories.Name = "ListCategories";
            this.ListCategories.Size = new System.Drawing.Size(220, 535);
            this.ListCategories.SmallImageList = this.CategoryIcons;
            this.ListCategories.Sorting = System.Windows.Forms.SortOrder.Ascending;
            this.ListCategories.TabIndex = 0;
            this.ListCategories.TileSize = new System.Drawing.Size(64, 64);
            this.ListCategories.UseCompatibleStateImageBehavior = false;
            this.ListCategories.SelectedIndexChanged += new System.EventHandler(this.ListCategories_SelectedIndexChanged);
            this.ListCategories.DoubleClick += new System.EventHandler(this.ListCategories_DoubleClick);
            // 
            // MenuCategoriesContext
            // 
            this.MenuCategoriesContext.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.MenuCategoriesContextAction});
            this.MenuCategoriesContext.Name = "MenuCategoriesContext";
            this.MenuCategoriesContext.ShowImageMargin = false;
            this.MenuCategoriesContext.Size = new System.Drawing.Size(113, 26);
            this.MenuCategoriesContext.Opening += new System.ComponentModel.CancelEventHandler(this.MenuCategoriesContext_Opening);
            // 
            // MenuCategoriesContextAction
            // 
            this.MenuCategoriesContextAction.Name = "MenuCategoriesContextAction";
            this.MenuCategoriesContextAction.Size = new System.Drawing.Size(112, 22);
            this.MenuCategoriesContextAction.Text = "Action Here";
            this.MenuCategoriesContextAction.Click += new System.EventHandler(this.MenuCategoriesContextAction_Click);
            // 
            // CategoryIcons
            // 
            this.CategoryIcons.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("CategoryIcons.ImageStream")));
            this.CategoryIcons.TransparentColor = System.Drawing.Color.Transparent;
            this.CategoryIcons.Images.SetKeyName(0, "astronomy.png");
            this.CategoryIcons.Images.SetKeyName(1, "biology.png");
            this.CategoryIcons.Images.SetKeyName(2, "chemistry.png");
            this.CategoryIcons.Images.SetKeyName(3, "compsci.png");
            this.CategoryIcons.Images.SetKeyName(4, "geology.png");
            this.CategoryIcons.Images.SetKeyName(5, "material.png");
            this.CategoryIcons.Images.SetKeyName(6, "medicine.png");
            this.CategoryIcons.Images.SetKeyName(7, "physics.png");
            this.CategoryIcons.Images.SetKeyName(8, "social.png");
            // 
            // ListViewTechs
            // 
            this.ListViewTechs.ContextMenuStrip = this.MenuTechnologiesContext;
            this.ListViewTechs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ListViewTechs.HideSelection = false;
            this.ListViewTechs.LargeImageList = this.IconList;
            this.ListViewTechs.Location = new System.Drawing.Point(0, 0);
            this.ListViewTechs.Name = "ListViewTechs";
            this.ListViewTechs.Size = new System.Drawing.Size(556, 535);
            this.ListViewTechs.SmallImageList = this.IconList;
            this.ListViewTechs.Sorting = System.Windows.Forms.SortOrder.Ascending;
            this.ListViewTechs.TabIndex = 0;
            this.ListViewTechs.TileSize = new System.Drawing.Size(128, 128);
            this.ListViewTechs.UseCompatibleStateImageBehavior = false;
            this.ListViewTechs.DoubleClick += new System.EventHandler(this.ListViewTechs_DoubleClick);
            // 
            // MenuTechnologiesContext
            // 
            this.MenuTechnologiesContext.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.MenuTechnologiesContextAction});
            this.MenuTechnologiesContext.Name = "MenuTechnologiesContext";
            this.MenuTechnologiesContext.Size = new System.Drawing.Size(138, 26);
            this.MenuTechnologiesContext.Opening += new System.ComponentModel.CancelEventHandler(this.MenuTechnologiesContext_Opening);
            // 
            // MenuTechnologiesContextAction
            // 
            this.MenuTechnologiesContextAction.AutoSize = false;
            this.MenuTechnologiesContextAction.Name = "MenuTechnologiesContextAction";
            this.MenuTechnologiesContextAction.Size = new System.Drawing.Size(251, 22);
            this.MenuTechnologiesContextAction.Text = "Action Here";
            this.MenuTechnologiesContextAction.Click += new System.EventHandler(this.MenuTechnologiesContextAction_Click);
            // 
            // exportIconsToolStripMenuItem
            // 
            this.exportIconsToolStripMenuItem.Name = "exportIconsToolStripMenuItem";
            this.exportIconsToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.exportIconsToolStripMenuItem.Text = "Export Icons";
            this.exportIconsToolStripMenuItem.Click += new System.EventHandler(this.ExportIconsToolStripMenuItem_Click);
            // 
            // FormMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.Panels);
            this.Controls.Add(this.menuStrip1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.MainMenuStrip = this.menuStrip1;
            this.MinimumSize = new System.Drawing.Size(800, 600);
            this.Name = "FormMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "TechEdit";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.FormMain_Load);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.Panels.Panel1.ResumeLayout(false);
            this.Panels.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.Panels)).EndInit();
            this.Panels.ResumeLayout(false);
            this.MenuCategoriesContext.ResumeLayout(false);
            this.MenuTechnologiesContext.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem openTechFileToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator saveToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem SaveTechFile;
        private System.Windows.Forms.ToolStripMenuItem SaveAsTechFile;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem2;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ImageList IconList;
        private System.Windows.Forms.SplitContainer Panels;
        private System.Windows.Forms.ListView ListViewTechs;
        private System.Windows.Forms.ListView ListCategories;
        private System.Windows.Forms.ContextMenuStrip MenuCategoriesContext;
        private System.Windows.Forms.ToolStripMenuItem MenuCategoriesContextAction;
        private System.Windows.Forms.ToolStripMenuItem CloseTechFile;
        private System.Windows.Forms.ImageList CategoryIcons;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ContextMenuStrip MenuTechnologiesContext;
        private System.Windows.Forms.ToolStripMenuItem MenuTechnologiesContextAction;
        private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem exportIconsToolStripMenuItem;
    }
}

